### ISSUE TITLE
Plugin nefunguje na kodi 15.2 pod Androidem

### ISSUE THREAD

**Issue by Jindrar** [alladdin/plugin.video.primaplay#1]
Plugin nefunguje na kodi 15.2 pod Androidem hlásí chybu : malformed start tag, at line 103, column 43.
Nešlo by to prosím opravit?  Celou strukturu a náhledy videí vidím, ale video nelze spustit. Díky.

Jinak ke kvalitě videa nešlo by použít  zdroje z FreeRapid downloaderu? Viz http://wordrider.net/forum/10/16873/iprima_plugin. Tam se jim nějak podařilo kvalitu videa vyřešit, takže lze stahovat soubory až 1080p. Vůbec tomu nerozumím, ale třeba by to pomůže. Přikládám plugin z FreeRapidu.

[iprima.zip](https://github.com/alladdin/plugin.video.primaplay/files/91899/iprima.zip)

**Comment by alladdin** [comment]
Jakou pozivas verzi pluginu?

Prosim otestuj posledni verzi z http://kodi-czsk.github.io/repository/

K te kvalite videa - kouknu na to, nechci nic slibovat, ale vypada to, ze by to mohlo jit

**Comment by Jindrar** [comment]
Promiň, nevšiml  jsem si, že na tabletu se mi doplněk neaktuazoval,  takže ty chybové hlášky neplatí.
Všechno funguje výborně.

**Comment by alladdin** [comment]
To je dobre.

Jinak v nove verzi pluginu je prehravani v hd (pokud je dostupne).

Dekuji za nasmerovani jak na forum, kde to resili.
