### ISSUE TITLE
Nefunguje Prima play verze 3.6

### ISSUE THREAD

**Issue by J-Pop** [alladdin/plugin.video.primaplay#10]
Při pokusu přehrát jakékoliv video s Prima Play vyhlásí kodi chybu: **NoneType object has no attribute group**. Zkoušeno na Samsung S4 android a Win 7 PC v různých sítích, všude stejná chyba.

**Comment by Majkie1** [comment]
Věřím že chyba je v tomhle http://api.play-backend.iprima.cz , čili změna url na iprima. Ale autor bude vědět více.
