### ISSUE TITLE
SSL error 

### ISSUE THREAD

**Issue by ToKroCZ** [alladdin/plugin.video.primaplay#11]
Po kliknutí na pořad na základní obrazovce dojde pouze k zobrazení chyby <urlopen error> [SSL: CERTIFICATE_VERIFY_FAILED]. Chyba je přítomna na čisté instalaci Kodi 17.1 na Androidu 7.1 i na Windows Server 2012. Na PC s Windows 10 mi to nějakým zázrakem funguje.

**Comment by alladdin** [comment]
Ve verzi 0.3.8 by to mělo být opraveno

**Comment by ToKroCZ** [comment]
Potvrzuji funkčnost opravy na obou zmíněných platformách 👍. Má sestra ti děkuje :D

**Comment by alladdin** [comment]
Není zač 😃
