### ISSUE TITLE
Nefunknční a následné přehrání

### ISSUE THREAD

**Issue by zabak79** [alladdin/plugin.video.primaplay#12]
Zdravím,
    mám na RPi OpenELEC 8 (Kodi 17.3) a doplněk Prima Play verze 0.3.8. Při pokusu o nalezení seriálu Živí mrtví si vyberu nalezenou epizodu, ale již ji nemohu přehrát. V čem je problém?

Děkuji za odpověď

**Comment by alladdin** [comment]
Problem je, ze na iprima pridali okno o obsahu pro dospele, ktere jsem jeste neporesil. Snad nejak do tydne se na to kouknu.

**Comment by alladdin** [comment]
Tak to vypada, ze stacilo pridat spravne cookies a uz by to melo chodit ve verzi 0.3.9
