### ISSUE TITLE
Kodi na raspberry pi a primaplay plugin bez obrazu

### ISSUE THREAD

**Issue by PeterMacko** [alladdin/plugin.video.primaplay#2]
Mam raspbery pi B na nom raspbian a kodi 15.1. Predchadzajuca verzia Prima PLAY pluginu mi fungovala fajn. S novou verziou mam vsak problem. Je uplne jedno ktore video spustim vzdy sa spusti iba zvuk bez obrazu (neukaze sa ziadna chyba). ostatne pluginy ako joj markiza atd funuju bez problemov. novy prima play plugin mam vo verzii 0.3.0. 
Nemas nejaku ideu kde by mohol byt problem?

**Comment by alladdin** [comment]
Zkus si vypnout HD v nastaveni. To by mohl byt tvuj problem.

**Comment by PeterMacko** [comment]
dik pomohlo
