### ISSUE TITLE
Corrupted playing

### ISSUE THREAD

**Issue by feflo** [alladdin/plugin.video.primaplay#4]
...on my devices (not a same - 3 kinds, but all on android) playback is corrupted after 3-14 mins...in old version was no problem...i am signed on prima account...

**Comment by feflo** [comment]
...napíšu to česky - anglicky stejně moc neumím - přehrávání se co 3-14 minut vypíná, přestože jsem přihlášen na účet Primy...dělá mi to na 3 různých Android zařízeních...minulá verze pluginu tímto problémem netrpěla...

**Comment by feflo** [comment]
...napíšu to česky - anglicky stejně moc neumím - přehrávání se co 3-14 minut vypíná, přestože jsem přihlášen na účet Primy...dělá mi to na 3 různých Android zařízeních...minulá verze pluginu tímto problémem netrpěla...

**Comment by feflo** [comment]
...napíšu to česky - anglicky stejně moc neumím - přehrávání se co 3-14 minut vypíná, přestože jsem přihlášen na účet Primy...dělá mi to na 3 různých Android zařízeních...minulá verze pluginu tímto problémem netrpěla...

**Comment by feflo** [comment]
...napíšu to česky - anglicky stejně moc neumím - přehrávání se co 3-14 minut vypíná, přestože jsem přihlášen na účet Primy...dělá mi to na 3 různých Android zařízeních...minulá verze pluginu tímto problémem netrpěla...

**Comment by feflo** [comment]
...napíšu to česky - anglicky stejně moc neumím - přehrávání se co 3-14 minut vypíná, přestože jsem přihlášen na účet Primy...dělá mi to na 3 různých Android zařízeních...minulá verze pluginu tímto problémem netrpěla...

**Comment by feflo** [comment]
...napíšu to česky - anglicky stejně moc neumím - přehrávání se co 3-14 minut vypíná, přestože jsem přihlášen na účet Primy...dělá mi to na 3 různých Android zařízeních...minulá verze pluginu tímto problémem netrpěla...

**Comment by alladdin** [comment]
Mohl bys prosím zkusit vypnout HD (v nastavení) na těch zařízeních, kde ti to nefunguje? Mohlo by to pomoci.

**Comment by feflo** [comment]
Dobrý den. 



... to jsem zkusil hned, jako 1. a pak se následně zaregistrovat a 
přihlásit... nepomohlo nic ale zjistil jsem, že interval přerušení se 
zkracuje - nejdříve to vydrží cca 10 - 14 min., pak čím dál kratší dobu... a
pak ztratím trpělivost... 



Děkuji za odpověď - tuto a i případnou následující. 



Struška. 



---------- Původní zpráva ----------

Od: Ladislav Dokulil 

Datum: 5. 2. 2016 v 11:10:16

Předmět: Re: [plugin.video.primaplay] Corrupted playing (#4)





Mohl bys prosím zkusit vypnout HD (v nastavení) na těch zařízeních, kde ti 
to nefunguje? Mohlo by to pomoci.

—

Reply to this email directly or view it on GitHub
(https://github.com/alladdin/plugin.video.primaplay/issues/4#issuecomment-180282945)
. 





=

**Comment by feflo** [comment]
Dobrý den. 



Tak jsem to zkusil i na OpenElec-u a je to prakticky to stejné, jen interval
je víceméně pravidelný - cca 3 - 4 minuty. 



Do internetu jsem připojen po optice, teor. rychlost 100 Mb (v praxi bývá 
mezi 70 - 90), doma Gb Lan, vše připojeno kabely... 



Děkuji. 



---------- Původní zpráva ----------

Od: Ladislav Dokulil 

Datum: 5. 2. 2016 v 11:10:16

Předmět: Re: [plugin.video.primaplay] Corrupted playing (#4)





Mohl bys prosím zkusit vypnout HD (v nastavení) na těch zařízeních, kde ti 
to nefunguje? Mohlo by to pomoci.

—

Reply to this email directly or view it on GitHub
(https://github.com/alladdin/plugin.video.primaplay/issues/4#issuecomment-180282945)
. 





=

**Comment by alladdin** [comment]
Můžeš prosím poslat kodi.log po tom co se přehrávač vypne?

Psal si, že minulá verze to nedělala? Která? Minulá verze mého pluginu, nebo ten který fungoval se starým webem primy?
