### ISSUE TITLE
Nektere porady nelze prehravat

### ISSUE THREAD

**Issue by Mulderr2** [alladdin/plugin.video.primaplay#5]
Dobry den, pouzivam tento plugin na Raspberry-XBMC-KODI_OpenElec. Od vydání nove verze nejdou prehravat nektere porady. Zkuste vyfiltrovat např. Prima ZOOM a spustit porad "Cestovani cervi dirou s morganem Freemanem" Nedostanete vůbec moznost prehrat tento porad. Dalo by se s tim něco udelat? Dekuji

**Comment by alladdin** [comment]
Podivam se na to.

**Comment by alladdin** [comment]
Byl tam drobný problém, že nešlo přehrát videa která neměla obrázek. To jsem opravil. Napiš jestli to pomohlo.

**Comment by Mulderr2** [comment]
Ano. Vypada to dobre. Diky za rychlou reakci
