### ISSUE TITLE
Nejde prehrat zadne video

### ISSUE THREAD

**Issue by marrier** [alladdin/plugin.video.primaplay#8]
Zdravím.
Nejde mi přehrát žádné video v doplňku Prima Play na Androidu (zkoušeno na celkem 2 zařízeních - tablet => Android 5.1, TV Box Minix X6 => Android 4.4.2). 

V PC (notebook => Win 7) to bez problémů přehraje. 

Na všech zařízeních je stejná verze Kodi, stejná verze doplňku. Dokonce i skiny a nastavení mám synchro. 

Přitom doplňkem normálně listuju, seznam videí vidím, ale jakmile kliknu na Přehrát, nestane se nic a po chvíli vyskočí error. Na PC se stejná položka přehraje téměř ihned po kliknutí.

Za jakékoliv rady díky moc.

Kompletní log k tomuto: https://paste.ubuntu.com/23506327/

PS: Jak jsem zjistil praktickym pokusem, neni chyba ani v aplikaci, ani v zarizeni, ale nekde mezi zarizenim a siti. Vyzkousel jsem oba Androidy (tablet i Minix) na jine siti (u rodicu), a tam se Prima Play bez problemu prehraje. Tipoval bych nejake nastaveni routeru (port apod.), ale absolutne netusim, kde hledat. Taky nechapu, ze to nefunguje jen na tech Androidech, zatimco na Win7 ano. Zrejme to pouziva trochu jiny zpusob pripojeni (jiny port apod.). Jsou to jen domnenky, zas tak hluboce nerozumim ani sitovani, ani jednotlivym OS. No, budu jeste delat pokusy a snad to nejak rozbeham, protoze Primu potrebuju.

Jen pro uplnost dodam, ze doma mam pripojeni O2 VDSL, zatimco rodice maji T-Mobile ADSL, ale to by snad vliv mit nemelo, jede to na stejnych dratech.

**Comment by akzafira** [comment]
Mám naprosto stejný problém. Také jsem připojen přes O2 VDSL. Na stejné síti pod Windows 10 vše funguje a na android zařízení nefunguje. Nějaký nápad?

**Comment by alladdin** [comment]
Bohužel mne nenapadá co by mohlo být špatně. Možná by pomohl kodi log.
A ještě bych zkusil, jestli video funguje v prohlizeci na androidu.

**Comment by marrier** [comment]
Odkaz na kompletni log k tomuto je v mem prispevku vyse a pridam ho tedy i sem: 
https://paste.ubuntu.com/23506327/

Jeste pripomenu, ze u jineho ISP mi Kodi jede (T-Mobile ADSL u rodicu), doma nikoliv (O2 VDSL).

**Comment by marrier** [comment]
V prohlizeci Androidu, stejne jako v original aplikaci Prima Play video jede, ale spatne a s hromadou reklam...

**Comment by akzafira** [comment]
Mám vícero zařízení různých značek na Androidu. Například MXQ Pro 4k s procesorem S905 Android 5.1, Dmyco-box  také Android 5.1 a procesor S905, X96 s procesorem S915 a Android 6.0. 
Bohužel ani v jednom zařízení v síti O2 plugin PrimaPlay nefunguje. Načte strukturu pořadů, jsou vidět náhledy pořadů, ale video nejde spustit. 
V té samé síti na PC plugin funguje naprosto báječně. 
Přímo v androidu, v aplikaci z GooglePlay video jde spustit. Z webové stránky Prima lze video také spustit.
[https://paste.ubuntu.com/23838512/](url)
 začína to někde od řádku 100.

**Comment by marrier** [comment]
Myslim, ze je celkem jasne, ze na vine neni plugin samotny, ale O2 a zrejme jejich nastaveni portu nebo neceho takoveho v routeru (laicky nazor, nejsem odbornik na sit). Doplnim proto, ze mam router Comtrend VR-3026e v2 Multi DSL a zajimalo by me, jaky mate vy ostatni. A pokud se v sitovani nekdo orientuje, at poradi, kde v tom hledat a pripadne co a jak prenastavit.

**Comment by akzafira** [comment]
Tak úplně s tím nesouhlasím. Jak jsem již psal, na stejné síti je PC  a tam plugin funguje velmi dobře. VDSL modem/Router mám stejný jako v příspěvku dole.
Mirek
______________________________________________________________
> Od: marrier <notifications@github.com>
> Komu: "alladdin/plugin.video.primaplay" <plugin.video.primaplay@noreply.github.com>
> Datum: 22.01.2017 22:36
> Předmět: Re: [alladdin/plugin.video.primaplay] Nejde prehrat zadne video (#8)
>
> CC: <comment@noreply.github.com>
Myslim, ze je celkem jasne, ze na vine neni plugin samotny, ale O2 a zrejme jejich nastaveni portu nebo neceho takoveho v routeru (laicky nazor, nejsem odbornik na sit). Doplnim proto, ze mam router Comtrend VR-3026e v2 Multi DSL a zajimalo by me, jaky mate vy ostatni. A pokud se v sitovani nekdo orientuje, at poradi, kde v tom hledat a pripadne co a jak prenastavit.

**Comment by alladdin** [comment]
Tak jsem na tom stejne jako vy. Taky O2 VDSL a VR-3026e a taky mi to na androidu nejede, ale jednu dobu to jelo.
Tim, ze to mam jak testovat, tak se snad doberu nejakyho vysledku. Dam vedet, az na neco prijdu.

**Comment by marrier** [comment]
To akzafira: To se nerozporuje. Je totiž pravděpodobné, že PC komunikuje na jiných parametrech, než Android. A v tom bych viděl jádro problému. Pak může určité nastavení routeru bránit správnému spojení.

**Comment by alladdin** [comment]
Tak zatim jsem se nikam moc nepohnul.
Na o2 i mimo nej plugin vraci stejne url pro prehravani do kodi aplikace DVDPlayer.
Na o2, DVD player vybere kvalitu a nasledne si pozada o seznam videi pro prehravani coz dopadne "403 forbidden".
Mimo o2 se seznam videi stahne a zacne prehravat.

Takze problem nastane v interni aplikaci DVDPlayer, ale vubec nevim proc.

Provedu jeste par pokusu, ale obavam se, ze na to neprijdu.

**Comment by alladdin** [comment]
Jeste kdyby nekdo vyzkousel zakazat ipv6 na routeru. Treba to pomuze.

**Comment by akzafira** [comment]
iPV6 vypnout nepomohlo

**Comment by ToKroCZ** [comment]
Absolutně tomu nerozumím, ale pokud je chyba v interním DVDPlayeru, tak ten je v Kodi 17 nahrazen modernější alternativou. Třeba se to vyřeší tím?

**Comment by alladdin** [comment]
Tak jsem vyzkousel kodi 17 na androidu a to funguje
