### ISSUE TITLE
Nefunguje

### ISSUE THREAD

**Issue by GustavoXPS** [alladdin/plugin.video.primaplay#9]
Zdarec chlapci, z nějakého důvodu nepřehrává žádná videa. Že by Prima udělala nějakou změnu na webu?

**Comment by Majkie1** [comment]
http://api.play-backend.iprima.cz/prehravac/ je problém v tomto, Alladdine?

**Comment by alladdin** [comment]
Problém byl opravdu ve výše uvedeném linku a ještě byl menší rozdíl ve struktuře.
